name: Claude OAuth Debug

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-oauth-debug:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Debug OAuth Tokens
        run: |
          echo "Debugging OAuth tokens..."
          echo "ACCESS_TOKEN length: ${#CLAUDE_ACCESS_TOKEN}"
          echo "REFRESH_TOKEN length: ${#CLAUDE_REFRESH_TOKEN}"
          echo "EXPIRES_AT: $CLAUDE_EXPIRES_AT"
          echo "Current timestamp: $(date +%s)000"
          echo "Current time: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

          if [ -n "$CLAUDE_EXPIRES_AT" ]; then
            expires_seconds=$((CLAUDE_EXPIRES_AT / 1000))
            echo "Token expires: $(date -u -d @$expires_seconds +%Y-%m-%dT%H:%M:%SZ)"
            current_seconds=$(date +%s)
            if [ $expires_seconds -lt $current_seconds ]; then
              echo "❌ Token is expired!"
            else
              echo "✅ Token is still valid"
            fi
          fi
        env:
          CLAUDE_ACCESS_TOKEN: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          CLAUDE_REFRESH_TOKEN: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          CLAUDE_EXPIRES_AT: ${{ secrets.CLAUDE_EXPIRES_AT }}

      - name: Run Claude Code with OAuth
        uses: Akira-Papa/claude-code-action@beta
        with:
          use_oauth: "true"
          claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
          timeout_minutes: "30"
